### ISSUE TITLE
File permission errors trying to build with go image

### ISSUE THREAD

**Issue by jlewi** [chainguard-images/go#16]
I was trying out chainguard go images and ran into permission errors when trying to run builds.

Here's the error.

```
go build github.com/somerepo/template/cmd: copying /tmp/go-build694225347/b001/exe/a.out: open /work/cli: permission denied
```

Here's my docker image.

```
# syntax=docker/dockerfile:1.4
ARG BUILD_IMAGE=cgr.dev/chainguard/go:latest
#ARG RUNTIME_IMAGE=cgr.dev/chainguard/static:latest
#ARG BUILD_IMAGE=golang:1.18
ARG RUNTIME_IMAGE=cgr.dev/chainguard/static:latest
FROM ${BUILD_IMAGE} as build

COPY go /work/go
WORKDIR /work/go

RUN ls -ld /work
#RUN echo "hello" > /work/somefile
RUN go build -o /work/cli ./cmd/...


FROM ${RUNTIME_IMAGE}

COPY --from=build /work/cli /cli
CMD ["/cli"]
```

Using `golang:1.18` as the image succeeds.  I'm building on GCB using the kaniko executor.

I tried the docker executor and got the same error.

For reference here's my cloudbuild.yaml

```
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'images/Dockerfile'
      - '.' 
# - name: 'gcr.io/kaniko-project/executor:latest'
#   args:
#   - --destination=gcr.io/$PROJECT_ID/stemplate/template-image
#   - --dockerfile=images/Dockerfile
#   # Default cache is two weeks
#   - --cache=true
```
